### ISSUE TITLE
ERR_AVD_HOME_NOT_FOUND: No valid Android AVD home found. livereload not working

### ISSUE THREAD

**Issue by kumarh526** [ionic-team/native-run#100]
C:\users\USERNAME\ .android\avd
just create the avd folder in yours .android folder and then run command 
ionic Cordova run android --device --livereload

**Comment by Sheetal-3098** [comment]
After doing this faced another issue 

[native-run] Selected hardware device 3fc9069a7cf5
[native-run] Installing platforms\android\app\build\outputs\apk\debug\app-debug.apk...
[native-run] ERR_UNKNOWN: Non-zero exit code from adb: 1
[native-run]
[native-run]    More details for this error may be available online:
[native-run]
[native-run]    https://github.com/ionic-team/native-run/wiki/Android-Errors
[ERROR] An error occurred while running subprocess native-run.

        native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-d... exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.



what to do now??

**Comment by imhoffd** [comment]
Run with `--verbose` flag like it asks and then post the full output.
