### ISSUE TITLE
Improvement to the wiki page

### ISSUE THREAD

**Issue by jlegido** [ionic-team/native-run#116]
First of all many thanks to all the people involved in this project for their time.

I would like to suggest an improvement to the [wiki page](https://github.com/ionic-team/native-run/wiki/Android-Errors). I was unable to fork then submit a Pull Request, looks like that it's not possible yet for wikis.

Kindly add below text:

---------------
**ERR_AVD_HOME_NOT_FOUND**

Create the missing directory:

```
mkdir -p $HOME/.android/avd
```
---------------

[Credits](https://github.com/ionic-team/native-run/issues/63#issuecomment-509258498)

**Comment by imhoffd** [comment]
@jlegido This exists as a feature in native-run 1.1.0, so this documentation is no longer necessary. Please give 1.1.0 a try! Thanks for the suggestion.
