### ISSUE TITLE
Android list is not working

### ISSUE THREAD

**Issue by Gabriel-des** [ionic-team/native-run#183]
**Version:**
1.3.0

**Description:**
I'm trying to use the capacitor's livereload function in an Android emulator, but to no avail. I tried to get a list of devices on my computer, but none show up. My emulator comes up with `adb devices`, but when I try to use `npx native-run android --list` the console gives me an error and a link:

> `ERR_UNSUITABLE_API_INSTALLATION: No suitable API installation found.`

The link takes me to the [Ionic Native Wiki](https://github.com/ionic-team/native-run/wiki/Android-Errors), but the error is not even listed on the page.

When I try to use `ionic cap run android` the console asks me to choose the device, but none appears. 

**Command Output:**
npx native-run android --list

**SDK Info:**
```
SDK Location:         C:\Users\55499\AppData\Local\Android\Sdk
AVD Home:             C:\Users\55499\.android\avd

API Level:            30
Packages:             Android SDK Platform 30  platforms;android-30  3
                      Google APIs Intel x86 Atom System Image  system-images;android-30;google_apis;x86  9
                      Google Play Intel x86 Atom System Image  system-images;android-30;google_apis_playstore;x86  9
                      Sources for Android 30  sources;android-30  1


API Level:            29
Packages:             Android SDK Platform 29  platforms;android-29  5
(!) Missing Packages: Google Play Intel x86 Atom System Image  system-images;android-29;google_apis_playstore;x86  /.+/


API Level:            28
Packages:             Google Play Intel x86 Atom System Image  system-images;android-28;google_apis_playstore;x86  9
(!) Missing Packages: Android SDK Platform 28  platforms;android-28


Tools:

Android Emulator  emulator  30.6.5
Android SDK Build-Tools 28.0.3  build-tools;28.0.3  28.0.3
Android SDK Build-Tools 30.0.2  build-tools;30.0.2  30.0.2
Android SDK Build-Tools 30.0.3  build-tools;30.0.3  30.0.3
Android SDK Platform-Tools  platform-tools  31.0.2
Android SDK Tools  tools  26.1.1
SDK Patch Applier v4  patcher;v4  1
```

**Comment by leonardofmed** [comment]
I'm having the exactly same problem. I can see my emulator with `adb devices`, but can't with `ionic capacitor run android  --list` or `npx native-run android --list`.
