### ISSUE TITLE
(documentation) The wiki page for Android should mention --verbose

### ISSUE THREAD

**Issue by kisaragi-hiu** [ionic-team/native-run#194]
##### Request

https://github.com/ionic-team/native-run/wiki/Android-Errors should mention the `--verbose` option to troubleshoot SDK path issues, for example by adding a paragraph like this:

> **ERR_UNSUITABLE_API_INSTALLATION**
>
> [...]
>
> There is also a possibility that the SDK path is incorrectly configured. You can check where native-run is looking by using the `--verbose` option:
>
> ```sh
> npx native-run android --list --verbose
> ```

##### Narrative

I was trying to install capacitor on my Linux machine and couldn't find a way to get `npx cap run android` to work. It would fail with this message, linking to [this page](https://github.com/ionic-team/native-run/wiki/Android-Errors):

```
[error] native-run failed with errors

        ERR_UNSUITABLE_API_INSTALLATION: No suitable API installation found.
        ENOENT: undefined

        More details for this errors may be available online:
        https://github.com/ionic-team/native-run/wiki/Android-Errors
```

After digging into the Capacitor command in `node_modules/@capacitor` and inserting print statements, I was able to nail the issue down to this line

```javascript
const output = await runNativeRun([platformName, '--list', '--json']);
```

and finally figure out what command Capacitor is relying on and where to insert my `--verbose`. After running `npx native-run android --list --verbose`, I finally found out, through this debug message:

```
  native-run:android:utils:sdk:resolveSDKRoot Looking for $ANDROID_HOME +0ms
  native-run:android:utils:sdk:resolveSDKRoot Using $ANDROID_HOME at /opt/android-sdk +3ms
```

that I have a leftover environment variable `ANDROID_HOME` set and that's why native-run cannot find the SDK.

If `npx native-run android --list --verbose` was mentioned on the Wiki page, I (and by extension those trying to figure out where to install the SDK) wouldn't have to dig into the built files just to figure this out.

**Comment by jcesarmobile** [comment]
I just added it to the wiki.
