### ISSUE TITLE
ERR_UNSUITABLE_API_INSTALLATION on MacBook Pro M1 Chip

### ISSUE THREAD

**Issue by Heriberto-Juarez** [ionic-team/native-run#196]
**Version:**

1.4.0

**Description:**

I've a Nuxt.js project. And im using capacitor to create a hybrid app. 
https://capacitorjs.com/docs/getting-started#adding-capacitor-to-an-existing-web-app
This iOS tutorial is working fine:
https://capacitorjs.com/docs/ios
Works:
npx cap run ios  

But android is not working:
https://capacitorjs.com/docs/android
Not working:
npx cap run android 

**Command Output:**

\W $npx cap run android --verbose
✔ Copying web assets from dist to android/app/src/main/assets/public in 464.43ms
✔ Creating capacitor.config.json in android/app/src/main/assets in 1.53ms
✔ copy android in 482.63ms
✔ Updating Android plugins in 2.92ms
✔ update android in 29.55ms
[error] native-run failed with error
        
        ERR_UNSUITABLE_API_INSTALLATION: No suitable API installation found.
        
        More details for this error may be available online:
        https://github.com/ionic-team/native-run/wiki/Android-Errors
        
\W $

**SDK Info:**

SDK Location:         /Users/aton/Library/Android/sdk
AVD Home:             /Users/aton/.android/avd

API Level:            31
Packages:             Android SDK Platform 31  platforms;android-31  1
                      Google APIs ARM 64 v8a System Image  system-images;android-31;google_apis;arm64-v8a  6

Tools:

Android Emulator  emulator  30.7.4
Android SDK Build-Tools 31  build-tools;31.0.0  31.0.0
Android SDK Platform-Tools  platform-tools  31.0.3
Android SDK Tools  tools  26.1.1
SDK Patch Applier v4  patcher;v4  1

**Comment by ricardo-valero** [comment]
I was having the same problem.
What they are saying in https://github.com/ionic-team/native-run/issues/195 is true and it should be added to the [docs](https://capacitorjs.com/docs/getting-started/environment-setup#android-development) or [wiki](https://github.com/ionic-team/native-run/wiki/Android-Errors). Personally, I would move the wiki to the docs.

First, I think the current supported API Level is 30, so make sure you install it `Preferences > Appearance & Behavior > System Settings > Android SDK > SDK Platforms`

Second, just try to run the emulator (create a blank project and `Tools > AVD Manager`)
I couldn't use the one that came when I downloaded Android Studio so you'd maybe have to *Create Virtual Device*, select a device, and select an image. Now you have two options x86 (which I haven't tried yet) and arm (if you get an error [Package “Android Emulator” with revision at least 30.8.0 not available](https://stackoverflow.com/questions/68774119/package-android-emulator-with-revision-at-least-30-8-0-not-available) use the Canary Channel in `Preferences > Appearance & Behavior > System Settings > Updates`)

**Comment by geocine** [comment]
I have setup everything, but still not working, I had to do this on Mac

```
cd ~/Library/Android/sdk/build-tools/31.0.0 && mv d8 dx && cd lib && mv d8.jar dx.jar
```
Source: https://stackoverflow.com/questions/68387270/android-studio-error-installed-build-tools-revision-31-0-0-is-corrupted

**Comment by gaurav21r** [comment]
This issue is because the Android SDK versions installed don't have the relevant images installed.
On `Android Studio` go to `SDK Manager` and make sure each SDK platform checked has the relevant system image also checked (and vice versa).

<img width="735" alt="image" src="https://user-images.githubusercontent.com/1716462/213266179-9eb62c55-c0b7-4ea3-a0eb-8ee13f30c30a.png">


If you want to know which packages are creating the problem for you, run `npm i -g native-run@latest` then `native-run android --sdk-info` in the root of your capacitor project directory.

Should solve it!
