### ISSUE TITLE
Typo on Wiki: "This menas the Android SDK"

### ISSUE THREAD

**Issue by TechplexEngineer** [ionic-team/native-run#226]
On this page of the wiki: https://github.com/ionic-team/native-run/wiki/Android-Errors

In the ERR_SDK_NOT_FOUND section https://github.com/ionic-team/native-run/wiki/Android-Errors#err_sdk_not_found

"This menas the Android SDK" should be "This means the Android SDK"

**Comment by jcesarmobile** [comment]
fixed, thanks!
