### ISSUE TITLE
The device rejected the pairing attempt

### ISSUE THREAD

**Issue by MarkAMcCorkle** [ionic-team/native-run#27]
Using the recommended new way to live reload run an ionic iOS app to device never runs on the device.
`ionic cordova run ios -l --address=0.0.0.0`

Doing a simpler `ionic cordova run ios` also never runs on the device.  

This is what actually runs from the console with no response. The app runs fine directly from Xcode.
`native-run ios --app platforms/ios/build/device/MyApp.ipa --connect --forward 8100:8100`
&
`native-run ios --app platforms/ios/build/device/MyApp.ipa`

ionic-info
Ionic:

   Ionic CLI                     : 5.0.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 5 other plugins)

Utility:

   cordova-res : 0.3.0
   native-run  : 0.2.1

System:

   Android SDK Tools : 26.1.1 (/Users/markmccorkle/Library/Android/sdk/)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v10.15.3 (/usr/local/Cellar/node@10/10.15.3/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001

**Comment by zakton5** [comment]
Having a similar issue. I'm getting this error when deploying to a device. It works fine on an emulator

```
TypeError: Cannot read property 'nodeName' of null
    at Object.parse (/Users/zkeeton/.nvm/versions/node/v10.16.0/lib/node_modules/native-run/node_modules/plist/lib/parse.js:68:25)
    at UsbmuxdClient.readPairRecord (/Users/zkeeton/.nvm/versions/node/v10.16.0/lib/node_modules/native-run/node_modules/node-ioslib/dist/client/usbmuxd.js:80:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by dwieeb** [comment]
@MarkAMcCorkle ` native-run ios --app platforms/ios/build/device/MyApp.ipa` has no output? Can you post the output of `native-run ios --app platforms/ios/build/device/MyApp.ipa --verbose` (if any)?

**Comment by MarkAMcCorkle** [comment]
@dwieeb The last lines showing in the terminal after running the requested command are below. 

  ```
client:usbmuxd connect: 1985 on port 62078 +2ms
  protocol:usbmux socket write: {"messageType":"Connect","extraFields":{"DeviceID":1985,"PortNumber":32498}} +1ms
  protocol:usbmux Response: {"MessageType":"Result","Number":0} +4ms
  client:lockdownd doHandshake +52ms
  client:lockdownd startSession: [object Object] +0ms
  protocol:lockdown socket write: {"Request":"StartSession","HostID":"3852AEBA-5540-48B3-95D1-66DBED6C94F2","SystemBUID":"0F16AC61-DAE9-4DFA-A521-39013E9FC82F"} +8ms
  protocol:lockdown Response: {"EnableSessionSSL":true,"Request":"StartSession","SessionID":"C78D3DBE-28D3-4795-968B-9481E1EDEB76"} +11ms
  client:lockdownd Socket upgraded to TLS connection +19ms
  client:lockdownd startService: com.apple.mobile.mobile_image_mounter +0ms
  protocol:lockdown socket write: {"Request":"StartService","Service":"com.apple.mobile.mobile_image_mounter"} +8ms
  protocol:lockdown Response: {"EnableServiceSSL":true,"Port":57299,"Request":"StartService","Service":"com.apple.mobile.mobile_image_mounter"} +64ms
  client:usbmuxd connectUsbmuxdSocket +87ms
  client:usbmuxd connect: 1985 on port 57299 +0ms
  protocol:usbmux socket write: {"messageType":"Connect","extraFields":{"DeviceID":1985,"PortNumber":54239}} +83ms
  protocol:usbmux Response: {"MessageType":"Result","Number":0} +4ms
  client:mobile_image_mounter lookupImage +0ms
  protocol:lockdown socket write: {"Command":"LookupImage","ImageType":"Developer"} +5ms
```

**Comment by MarkAMcCorkle** [comment]
**UPDATE**. I finally got the device to run the app although I still can't get live reload to work. However, this does at least let native-run finally run on the device without having to launch Xcode to run each time. Live-reload is still an issue (just sits at the ionic splash screen)
**SOLUTION**: (Only works for `ionic cordova run ios --device`without -l)
Enter iOS device settings app -> General -> Reset -> Reset Network Settings

**Comment by giladrom** [comment]
I have the same issue. Ionic 3 project with the latest CLI.

**Comment by dwieeb** [comment]
This issue occurs when the device rejects pairing because of trust settings between device & computer. When they're first connected, a prompt comes up to "Trust" or "Don't Trust", and the choice appears permanent unless all the network settings are reset. (Settings App on iOS device -> General -> Reset -> Reset Network Settings) as @MarkAMcCorkle mentioned.

**Comment by bnallmaster** [comment]
I went back to 4.12.0 CLI and live reload worked as expected (without logs of course).

**Comment by bnallmaster** [comment]
I am having a similar issue with Ionic CLI 5.0.0. I finally got it to build and got things updated and installed and the Livereload is not working. For a while I was getting an error that said nodeModule is null. I resolved that issue and both ionic cordova run ios and cordova run ios are launching the app. When I try ionic cordova run ios -l or --livereload it acts like it is building and no errors but it hangs on the splashscreen and won't go beyond that. I have been testing with this a majority of the day and has been difficult to nail down the issues. It also appears that the Legacy or New Build system in iOS is no longer important to it being able to build. I also tried the clearing the network settings on my iPhone and got a new Trust pop up that I accepted. It seemed to get closer after I did that but would stay loading on the splash screen. Yes I am using Angular. I got it to at least get past the splash screen but only on iOS emulator, NOT device, and there is no console logging with any of it.

**Comment by dwieeb** [comment]
@bnallmaster's issue is continued here: https://github.com/ionic-team/ionic-cli/issues/4008

**Comment by MarkAMcCorkle** [comment]
The latest native-run@0.2.4 has solved all my issues.

**Comment by markterrill** [comment]
This issue is occuring on 0.2.6. The last issue reported via --verbose is protocol:lockdown socket write: {"Command":"LookupImage","ImageType":"Developer"} +5ms

What resolved it for me:

- Settings > General > Reset > Reset privacy & location  (this is what resets computer trust, not network settings above)
- Unplug phone, replug. It should ask you if you trust the computer.  Interestingly that wasn't enough. I loaded up safari, went to the develop menu and chose the phone, 'use for development'. 

Then native-run would execute!

**Comment by michelepatrassi** [comment]
After running this 
```
ionic cordova run ios -l --device --external 
```

I had 
```
> cordova build ios --device --iCloudContainerEnvironment=Development
[cordova] 2020-01-08 10:54:23.848 xcodebuild[22002:2998977]  DTDeviceKit: deviceType from 00008030-0003142E3A90802E was NULL
[cordova] 2020-01-08 10:54:23.993 xcodebuild[22002:2999085]  DTDeviceKit: deviceType from 00008030-0003142E3A90802E was NULL
[cordova] 2020-01-08 10:54:24.180 xcodebuild[22002:2998977]  DTDeviceKit: deviceType from 00008006-0009350A1AEB002E was NULL
[cordova] 2020-01-08 10:54:28.173 xcodebuild[22002:2998977]  DTDeviceKit: Failed to mount DDI from '<DVTFilePath:0x7ffa38244040:'/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/DeviceSupport/6.1/DeveloperDiskImage.dmg'>', error=-402653183: Error Domain=com.apple.dtdevicekit Code=-402653183 "Xcode encountered an error" UserInfo={NSLocalizedFailureReason=An unknown error occurred., com.apple.dtdevicekit.stacktrace=(
[cordova]       0   DTDeviceKitBase                     0x00000001176556e7 DTDKCreateNSError + 109
[cordova]       1   DTDeviceKitBase                     0x0000000117655de9 DTDK_AMDErrorToNSError + 792
[cordova]       2   DTDeviceKitBase                     0x0000000117693780 -[DTDKMobileDeviceToken _mountDeveloperDiskImage:withError:] + 844
[cordova]       3   DTDeviceKitBase                     0x000000011769429d __58-[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:]_block_invoke + 699
[cordova]       4   libdispatch.dylib                   0x00007fff66acb50e _dispatch_client_callout + 8
[cordova]       5   libdispatch.dylib                   0x00007fff66ad7567 _dispatch_lane_barrier_sync_invoke_and_complete + 60
[cordova]       6   DTDeviceKitBase                     0x0000000117693f80 -[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:] + 199
[cordova]       7   IDEiOSSupportCore                   0x0000000117279107 __28-[DVTiOSDevice attachToken:]_block_invoke_4 + 254
[cordova]       8   DVTFoundation                       0x0000000107ec5e8a __DVT_CALLING_CLIENT_BLOCK__ + 7
[cordova]       9   DVTFoundation                       0x0000000107ec7562 __DVTDispatchAsync_block_invoke + 809
[cordova]       10  libdispatch.dylib                   0x00007fff66aca583 _dispatch_call_block_and_release + 12
[cordova]       11  libdispatch.dylib                   0x00007fff66acb50e _dispatch_client_callout + 8
[cordova]       12  libdispatch.dylib                   0x00007fff66acd6c0 _dispatch_continuation_pop + 414
[cordova]       13  libdispatch.dylib                   0x00007fff66accdbe _dispatch_async_redirect_invoke + 703
[cordova]       14  libdispatch.dylib                   0x00007fff66ad97e2 _dispatch_root_queue_drain + 326
[cordova]       15  libdispatch.dylib                   0x00007fff66ad9f22 _dispatch_worker_thread2 + 92
[cordova]       16  libsystem_pthread.dylib             0x00007fff66d256b6 _pthread_wqthread + 220
[cordova]       17  libsystem_pthread.dylib             0x00007fff66d24827 start_wqthread + 15
[cordova] ), DVTRadarComponentKey=487927, NSLocalizedDescription=Xcode encountered an error}
[cordova] 2020-01-08 10:54:28.174 xcodebuild[22002:2998977]  iPhoneSupport: 📱<DVTiOSDevice (0x7ffa3779cf30), Michels iphone, iPhone, 13.3 (17C54), 00008030-0003142E3A90802E> unable to mount DeveloperDiskImage (Error Domain=com.apple.dtdevicekit Code=-402653183 "Xcode encountered an error" UserInfo={NSLocalizedFailureReason=An unknown error occurred., com.apple.dtdevicekit.stacktrace=(
[cordova]       0   DTDeviceKitBase                     0x00000001176556e7 DTDKCreateNSError + 109
[cordova]       1   DTDeviceKitBase                     0x0000000117655de9 DTDK_AMDErrorToNSError + 792
[cordova]       2   DTDeviceKitBase                     0x0000000117693780 -[DTDKMobileDeviceToken _mountDeveloperDiskImage:withError:] + 844
[cordova]       3   DTDeviceKitBase                     0x000000011769429d __58-[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:]_block_invoke + 699
[cordova]       4   libdispatch.dylib                   0x00007fff66acb50e _dispatch_client_callout + 8
[cordova]       5   libdispatch.dylib                   0x00007fff66ad7567 _dispatch_lane_barrier_sync_invoke_and_complete + 60
[cordova]       6   DTDeviceKitBase                     0x0000000117693f80 -[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:] + 199
[cordova]       7   IDEiOSSupportCore                   0x0000000117279107 __28-[DVTiOSDevice attachToken:]_block_invoke_4 + 254
[cordova]       8   DVTFoundation                       0x0000000107ec5e8a __DVT_CALLING_CLIENT_BLOCK__ + 7
[cordova]       9   DVTFoundation                       0x0000000107ec7562 __DVTDispatchAsync_block_invoke + 809
[cordova]       10  libdispatch.dylib                   0x00007fff66aca583 _dispatch_call_block_and_release + 12
[cordova]       11  libdispatch.dylib                   0x00007fff66acb50e _dispatch_client_callout + 8
[cordova]       12  libdispatch.dylib                   0x00007fff66acd6c0 _dispatch_continuation_pop + 414
[cordova]       13  libdispatch.dylib                   0x00007fff66accdbe _dispatch_async_redirect_invoke + 703
[cordova]       14  libdispatch.dylib                   0x00007fff66ad97e2 _dispatch_root_queue_drain + 326
[cordova]       15  libdispatch.dylib                   0x00007fff66ad9f22 _dispatch_worker_thread2 + 92
[cordova]       16  libsystem_pthread.dylib             0x00007fff66d256b6 _pthread_wqthread + 220
[cordova]       17  libsystem_pthread.dylib             0x00007fff66d24827 start_wqthread + 15
[cordova] ), DVTRadarComponentKey=487927, NSLocalizedDescription=Xcode encountered an error})
[cordova] 2020-01-08 10:55:45.573 xcodebuild[24361:3003553] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/22/x7frqwq15tb3vx1xvdp5y9pc0000gn/T/Homerun_2020-01-08_10-55-45.572.xcdistributionlogs'.
> native-run ios --app platforms/ios/build/device/Homerun.ipa --device --forward 8100:8100
```

Because of the error, I was thinking that nothing was working at all. Then I waited and I had the app working anyway with live-reload on the device
