### ISSUE TITLE
ERR_UNSUPPORTED_API_LEVEL

### ISSUE THREAD

**Issue by m1212e** [ionic-team/native-run#286]
Hi,
I'm getting: 
```
[error] native-run failed with error

        ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 33x

        More details for this error may be available online:
        https://github.com/ionic-team/native-run/wiki/Android-Errors
```
looking up the error tells me to notify you guys about this here:
```
ERR_UNSUPPORTED_API_LEVEL

You are using an Android SDK that is not supported by native-run. Please, let us know by creating a new issue https://github.com/ionic-team/native-run/issues.

As workaround you can downgrade your installed Android SDK. Latest supported version is SDK 31.
```
So I'm just letting you guys know and will downgrade my SDK version for now.

**Comment by SDixit-MSC** [comment]
I'm getting the same error. I hope support for API 33 will come soon as I don't plan to downgrade.

**Comment by jcesarmobile** [comment]
API 33 is supported since version 1.7.0, the wiki was incorrect, I've updated it.

Not sure what 33x is, but it's not supported and it's not going to be supported, update to regular 33.

**Comment by max-sistemich-kisters** [comment]
FWIW, I had some problems switching to regular 33 as android studio automatically installs 33x and doesn't give any indication that it isn't regular 33.
I had to enable "Show Package Details" to see that it was in fact "Android 13.0 (Tiramisu), Extension Level 4" and to be able to uninstall it. Those are probably the versions that are [mentioned here](https://developer.android.com/guide/sdk-extensions).

![2023-02-10 09_08_02-Settings](https://user-images.githubusercontent.com/122873590/218039980-3ef39923-1ea2-41da-8d88-2ccd81bcc46d.png)

**Comment by Jarrodsz** [comment]
Also Have this issue... 
<img width="1080" alt="Screenshot 2023-03-15 at 18 36 28" src="https://user-images.githubusercontent.com/90145421/225396303-17a9bcb7-bdf0-43ee-96d4-ff0f91f74175.png">

```
npx cap run android
✔ Copying web assets from app to android/app/src/main/assets/public in 3.78ms
✔ Creating capacitor.config.json in android/app/src/main/assets in 722.92μs
[info] Inlining sourcemaps
✔ copy android in 60.14ms
✔ Updating Android plugins in 6.91ms
✔ update android in 21.47ms
[error] native-run failed with error

        ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 33x

        More details for this error may be available online:
        https://github.com/ionic-team/native-run/wiki/Android-Errors

```

variables: 
```

ext {
    minSdkVersion = 22
    compileSdkVersion = 30
    targetSdkVersion = 30
    androidxActivityVersion = '1.4.0'
    androidxAppCompatVersion = '1.4.2'
    androidxCoordinatorLayoutVersion = '1.2.0'
    androidxCoreVersion = '1.8.0'
    androidxFragmentVersion = '1.4.1'
    coreSplashScreenVersion = '1.0.0-rc01'
    androidxWebkitVersion = '1.4.0'
    junitVersion = '4.13.2'
    androidxJunitVersion = '1.1.3'
<img width="1080" alt="Screenshot 2023-03-15 at 18 36 28" src="https://user-images.githubusercontent.com/90145421/225396013-294e0f66-c0f3-4841-9380-bf4cc7ad9bbb.png">

    androidxEspressoCoreVersion = '3.4.0'
    cordovaAndroidVersion = '10.1.1'
}
```

It just keeps stubborn saying I have 33X.
Newbie dev wanted to try this, terrible dx, ios works fine though.

I have the SDK installed in my screenshot, even when i define in variables it will still say 33X stubborn.

Is this a bug, anyone knows a work around for this?

**Comment by Jarrodsz** [comment]
<img width="1080" alt="Screenshot 2023-03-15 at 18 36 28" src="https://user-images.githubusercontent.com/90145421/225396334-7406a53d-5410-498a-9d34-a7dd08f06cf4.png">
