### ISSUE TITLE
ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 33x

### ISSUE THREAD

**Issue by RedsTom** [ionic-team/native-run#303]
**Version:** 1.7.2

**Description:** Unable to launch an application on any emulator or device

**Command Output:** `ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 33x`

**SDK Info:**
```
SDK Location:         /home/redstom/Android/Sdk/
AVD Home:             /home/redstom/.android/avd

API Level:            33x
Packages:             Android SDK Platform 33-ext5  platforms;android-33-ext5  1


API Level:            30
Packages:             Google APIs Intel x86 Atom System Image  system-images;android-30;google_apis;x86  10
(!) Missing Packages: Android SDK Platform 30  platforms;android-30


API Level:            29
Packages:             Android SDK Platform 29  platforms;android-29  5
                      Sources for Android 29  sources;android-29  1
(!) Missing Packages: Google Play Intel x86 Atom System Image  system-images;android-29;google_apis_playstore;x86  /.+/


Tools:

Android Emulator  emulator  32.1.12
Android SDK Build-Tools 33.0.2  build-tools;33.0.2  33.0.2
Android SDK Platform-Tools  platform-tools  34.0.1
SDK Patch Applier v4  patcher;v4  1
```

**Comment by khromov** [comment]
I have the same problem. Launching via Android Studio works.

**Comment by patrick-tresp** [comment]
same here

**Comment by khromov** [comment]
@patrick-tresp I solved this by upgrading to Capacitor 5. Wrote a little about it over on Discord.

Here are the docs but they're a little bit wrong, see my comment later:
https://capacitorjs.com/docs/next/updating/5-0

https://discord.com/channels/520266681499779082/908091931295375380/1095795167635701800

<img width="984" alt="Screenshot 2023-04-13 at 19 17 56" src="https://user-images.githubusercontent.com/1207507/231835762-bac1c15e-f292-4f72-ad20-07b7a2edad24.png">

**Comment by Erudition** [comment]
I'm already using Capacitor 5. I just installed @nativescript/capacitor, though I didn't get the `src` folder created automatically. I figured I'd try running `nativescript-dev`, and this is what I get:

```
dev-nativescript android
[fatal] native-run failed with error

        ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 33x
  
        More details for this error may be available online: https://github.com/ionic-team/native-run/wiki/Android-Errors
  
file:///home/adroit/Projects/Minder/node_modules/.pnpm/@nativescript+capacitor@5.0.1_@types+node@20.1.4_esbuild@0.17.19_typescript@5.0.4_webpack@5.82.1/node_modules/@nativescript/capacitor/bin/dev-nativescript.mjs:42
        targetDevice = await prompts({
                     ^

ReferenceError: targetDevice is not defined
    at selectTargetDevice (file:///home/adroit/Projects/Minder/node_modules/.pnpm/@nativescript+capacitor@5.0.1_@types+node@20.1.4_esbuild@0.17.19_typescript@5.0.4_webpack@5.82.1/node_modules/@nativescript/capacitor/bin/dev-nativescript.mjs:42:22)
    at async file:///home/adroit/Projects/Minder/node_modules/.pnpm/@nativescript+capacitor@5.0.1_@types+node@20.1.4_esbuild@0.17.19_typescript@5.0.4_webpack@5.82.1/node_modules/@nativescript/capacitor/bin/dev-nativescript.mjs:82:24
```

**Comment by regetskcob** [comment]
@khromov I tried to upgrade, with this result...

<img width="1440" alt="Bildschirmfoto 2023-05-24 um 14 13 29" src="https://github.com/ionic-team/native-run/assets/52231719/1739a81d-37c8-405b-b15a-08ec1fe27efd">

I already submitted another ticket regarding the pod error. https://github.com/ionic-team/native-run/issues/315
