### ISSUE TITLE
[error] /bin/sh: pod: command not found

### ISSUE THREAD

**Issue by regetskcob** [ionic-team/native-run#315]
**Version:** 1.7.2

**Description:**

When I tried to start my iOS or Android app I always get the error message `[error] /bin/sh: pod: command not found`. I don't know whether cocoapods is meant there (does not make sense to me when building for android) but cocoapods is freshly installed and working.

<img width="682" alt="Bildschirmfoto 2023-05-24 um 13 49 31" src="https://github.com/ionic-team/native-run/assets/52231719/00f5dd25-f642-4e8f-8c20-7298874109f2">

**SDK Info:**

```
SDK Location:         /Users/dbocksteger/Library/Android/sdk
AVD Home:             /Users/dbocksteger/.android/avd

API Level:            33
Packages:             Android SDK Platform 33  platforms;android-33  2
                      Google APIs ARM 64 v8a System Image  system-images;android-33;google_apis;arm64-v8a  9
                      Sources for Android 33  sources;android-33  1


API Level:            31
Packages:             Android SDK Platform 31  platforms;android-31  1
                      Sources for Android 31  sources;android-31  1
(!) Missing Packages: Google Play Intel x86 Atom System Image  system-images;android-31;google_apis_playstore;x86  /.+/


Tools:

Android Emulator  emulator  32.1.13
Android SDK Build-Tools 33.0.2  build-tools;33.0.2  33.0.2
Android SDK Build-Tools 34-rc4  build-tools;34.0.0-rc4  34.0.0
Android SDK Command-line Tools (latest)  cmdline-tools;latest  9.0
Android SDK Platform-Tools  platform-tools  34.0.1
SDK Patch Applier v4  patcher;v4  1
```

**Comment by regetskcob** [comment]
Still no reaction on this critical issue in a blank setup?

**Comment by jcesarmobile** [comment]
native-run only runs the app you pass as a parameter, it doesn't build it and it doesn't use `pod` command anywhere, there isn't enough information to know what you are running, but it's not a native-run issue.
