### ISSUE TITLE
bug: ERR_UNSUITABLE_API_INSTALLATION

### ISSUE THREAD

**Issue by dvlpr91** [ionic-team/native-run#316]
package.json
<img width="372" alt="image" src="https://github.com/ionic-team/capacitor/assets/40349371/76e916c4-6c53-4fe5-aaa5-01bb515d8a50">

node version
<img width="250" alt="image" src="https://github.com/ionic-team/capacitor/assets/40349371/66822867-02a0-4dc4-be6b-c29115b8260f">

android sdk info
<img width="686" alt="image" src="https://github.com/ionic-team/capacitor/assets/40349371/5cb8d79d-f8a8-4135-b7d4-c29bccffb7c9">

result
<img width="718" alt="image" src="https://github.com/ionic-team/capacitor/assets/40349371/11417e24-84cc-41e9-a379-8bf8209e3421">

wow...

**Comment by jcesarmobile** [comment]
that means some SDK packages are missing, can you run the command with `--verbose` at the end? `native-run android --sdk-info --verbose`

**Comment by xlinxie** [comment]
```
export async function getDefaultAVDSchematic(sdk: SDK): Promise<AVDSchematic> {
  const debug = Debug(`${modulePrefix}:${getDefaultAVDSchematic.name}`);
  const packages = await findAllSDKPackages(sdk);
  const apis = await getAPILevels(packages);
  const errors: AVDException[] = [];

  for (const api of apis) {
    try {
      const schematic = await getAVDSchematicFromAPILevel(sdk, packages, api);
      debug('Using schematic %s for default AVD, API level: %s', schematic.id, api.apiLevel);

      return schematic;
    } catch (e) {
      if (!(e instanceof AVDException)) {
        throw e;
      }
      errors.push(e);
      debug('Issue with API %s: %s', api.apiLevel, e.message, e.code);
    }
  }

  if (errors.length > 0) {
    const unsupportedError = errors.find(
      e => e.code === ERR_UNSUPPORTED_API_LEVEL,
    );
    if (unsupportedError) {
      throw unsupportedError;
    }
  }

  throw new AVDException(
    'No suitable API installation found. Use --sdk-info to reveal missing packages and other issues.',
    ERR_UNSUITABLE_API_INSTALLATION,
    1,
  );
}
```

the `No suitable API installation found` error only throws by `getDefaultAVDSchematic`

`getAVDSchematicFromAPILevel` will validate sdk packages to check if any package is missing, but running `native-run android --sdk-info` does not show any missing packages. Some other `AVDException` may throwed out by `getDefaultAVDSchematic` and this error's code is not ERR_UNSUPPORTED_API_LEVEL, so it's not handled or throwed

try run `native-run android --sdk-info --verbose` to get more helpful info

**Comment by dvlpr91** [comment]
I left the ionic.
