### ISSUE TITLE
iOS 17 Support needed. 

### ISSUE THREAD

**Issue by jonasphp** [ionic-team/native-run#320]
**Version:**

1.7.2

**Description:**

Native run is not compatible with iOS 17, the command "npx cap run ios" is still working the app is deployed via CLI but status is failed due to errors in node_modules/native-run/dist/ios/lib/protocol/lockdown.js - Build works via xCode 15 Beta and launches successful. 

**Command Output:**
Error: InvalidService
        at LockdownProtocolReader.parseBody (/Users/jonas/Desktop/VAOW CAPACITOR/
        APP/node_modules/native-run/dist/ios/lib/protocol/lockdown.js:41:19)
        at LockdownProtocolReader.onData (/Users/jonas/Desktop/VAOW CAPACITOR/
        APP/node_modules/native-run/dist/ios/lib/protocol/protocol.js:53:40)
        at TLSSocket.emit (node:events:525:35)
        at addChunk (node:internal/streams/readable:324:12)
        at readableAddChunk (node:internal/streams/readable:297:9)
        at Readable.push (node:internal/streams/readable:234:10)
        at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)

**Environment Info:**

Ionic:

   Ionic CLI : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)

Capacitor:

   Capacitor CLI      : 5.0.3
   @capacitor/android : 5.0.3
   @capacitor/core    : 5.0.3
   @capacitor/ios     : 5.0.3

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.16.0 (/usr/local/bin/node)
   npm    : 9.5.1
   OS     : macOS Unknown

macOS version:
13.3.1
Xcode version:
15 Beta

**Comment by collindutter** [comment]
For those in need of a workaround, I was able to get it running via XCode:
`ionic cap run ios --open -l --external`

**Comment by ThodorisElissaios** [comment]
how to use devicectl ?

**Comment by miguelromeroh** [comment]
this works for me

> For those in need of a workaround, I was able to get it running via XCode: `ionic cap run ios --open -l --external`

**Comment by capc0** [comment]
not working for me (Xcode 15.0.1) due to https://github.com/ionic-team/native-run/pull/341#issuecomment-1770857017

**Comment by JulianAtTheFrontend** [comment]
Not working on Version 15.0.1

**Comment by stefano055415** [comment]
Not working on Version 15.0.1
