### ISSUE TITLE
API Level 34

### ISSUE THREAD

**Issue by haytham918** [ionic-team/native-run#322]
**Version:** 34

native-run failed with error
        
ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 34

**Description:**

Can't Build Android App

**Command Output:**

**SDK Info:**

SDK 34

**Comment by suiciniv87** [comment]
same problem

**Comment by Sebastiangperez** [comment]
Same here

**Comment by haytham918** [comment]
I solved this issue by downgrading to API level 33

**Comment by Sebastiangperez** [comment]
Yes , me too , thanks , weird. 
Question @haytham918 , do you have issues when you try to install an apk file while you have active Google Play Protect , even if you give the authorization that says install anyway ? i'm getting app not installed , if i disable Play Protect , works.

**Comment by warenix** [comment]
I found sometimes the error message `ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 34` is misleading.

Below error is shown when I unplug my android phone:

```sh
-> % npx cap run android
✔ Copying web assets from dist_android to android/app/src/main/assets/public in 20.70ms
✔ Creating capacitor.config.json in android/app/src/main/assets in 925.08μs
[info] Inlining sourcemaps
✔ copy android in 46.28ms
✔ Updating Android plugins in 3.80ms
✔ update android in 34.54ms
[error] native-run failed with error
        
        ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 34
        
        More details for this error may be available online:
        https://github.com/ionic-team/native-run/wiki/Android-Errors
```

After plugging in and making sure `adb devices` shows my phone, the app is then installed successfully:

```sh
-> % npx cap run android
✔ Copying web assets from dist_android to android/app/src/main/assets/public in 19.12ms
✔ Creating capacitor.config.json in android/app/src/main/assets in 857.67μs
[info] Inlining sourcemaps
✔ copy android in 40.55ms
✔ Updating Android plugins in 3.92ms
✔ update android in 27.36ms
✔ Running Gradle build in 1.32s
✔ Deploying app-debug.apk to *************  in 2.36s
```

**Comment by benhidi** [comment]
> I solved this issue by downgrading to API level 33

can you show me how

**Comment by haytham918** [comment]
In your Android Studio, download target SDK and image that is 33

**Comment by pablopereira27** [comment]
This problem happens because "Run Android" is trying to run the application on an AVD (Android Virtual Device) API 34, if you remove or edit this AVD to API 33 or run the app on a non-virtual device through the cable connected to the computer (adb devices), this problem ends.

Obviously you need:
- Have SDK 33 and the System Image (Google APIs Intel x86_64 Atom System Image), both of which can be acquired through the SDK Manager contained in Android Studio.
- Create the AVD with API 33.

**Comment by 9705409705** [comment]
Unable to find any devices: [fatal] native-run failed with error ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 34

**Comment by gkpo** [comment]
@haytham918 

> In your Android Studio, download target SDK and image that is 33

In my SDK Manager, the version that has API Level 33 is Android 13.0 ("Tiramisu"). Is this the right one ?
I then pick the 2 sub items:
- Android SDK Platform 33
- Sources for Android 33

And I download them. But then when I run `npx cap run android` I get this error:

> ERR_UNSUITABLE_API_INSTALLATION: No suitable API installation found. Use --sdk-info to reveal missing packages and other issues.

Any ideas ?

**Comment by jcesarmobile** [comment]
You also need to download an emulator image, but it's better if you just update native-run to version 2.0.0 as it no longer requires an emulator image

**Comment by gkpo** [comment]
@jcesarmobile thanks for your help, I also just figured that out.
It solved this issue but now I have another one...

> Could not open settings generic class cache for settings file
> '/Users/...path-to-app.../android/settings.gradle'

So I guess my search continues on different forums.... I wonder when developers will finally be freed from dependency hell and will be able to focus on building apps... Setting up a working environment from the first go almost seems like utopia.

**Comment by lefa01** [comment]
**![Uploading Screenshot 2023-11-27 at 11.24.39 AM.png…]()**

**Comment by GamerQuanTuM** [comment]
√ update android in 81.49ms
[error] native-run failed with error
More details for this error may be available online:
https://github.com/ionic-team/native-run/wiki/Android-Errors
