### ISSUE TITLE
ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 34

### ISSUE THREAD

**Issue by iamsouravganguli** [ionic-team/native-run#323]
[error] native-run failed with error

ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 34

**Comment by xlinxie** [comment]
native-run will try to create a AVD for the lastest valid SDK from schema template if that AVD is not found, and for the time being there is no AVD schema template for SDK 34. You may have only SDK 34 installed, so native-run failed to create default AVD schema for it and throws `ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 34`

try install SDK 33 and run it again

**Comment by iamsouravganguli** [comment]
> native-run will try to create a AVD for the lastest valid SDK from schema template if that AVD is not found, and for the time being there is no AVD schema template for SDK 34. You may have only SDK 34 installed, so native-run failed to create default AVD schema for it and throws `ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 34`
> 
> try install SDK 33 and run it again

thank you for replied
i solved my problem with some minor changes

**Comment by kevincam3** [comment]
> > native-run will try to create a AVD for the lastest valid SDK from schema template if that AVD is not found, and for the time being there is no AVD schema template for SDK 34. You may have only SDK 34 installed, so native-run failed to create default AVD schema for it and throws `ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 34`
> > try install SDK 33 and run it again
> 
> thank you for replied i solved my problem with some minor changes

How did you solve this problem?
