### ISSUE TITLE
ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 33x

### ISSUE THREAD

**Issue by humayunalerts** [ionic-team/native-run#332]
**Version:**

5.2.2

**Description:**

[error] native-run failed with error

        ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 33x       

**Command Output:**

[error] native-run failed with error

        ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 33x

**SDK Info:**

$ npx cap run android --sdk-info
√ Copying web assets from build to android\app\src\main\assets\public in 148.40ms
√ Creating capacitor.config.json in android\app\src\main\assets in 2.81ms
[info] Inlining sourcemaps
√ copy android in 378.14ms
√ Updating Android plugins in 25.00ms
√ update android in 149.92ms
[error] native-run failed with error

        ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 33x

**Comment by teamzz111** [comment]
+1

**Comment by Ug48** [comment]
+1 facing same issue
