### ISSUE TITLE
 ERR_UNSUPPORTED_API_LEVEL Android 14 Upside Down Cake

### ISSUE THREAD

**Issue by codingscenes** [ionic-team/native-run#372]
**Version:** 

√ Copying web assets from dist to android\app\src\main\assets\public in 25.14ms
√ Creating capacitor.config.json in android\app\src\main\assets in 1.13ms
[info] Inlining sourcemaps
√ copy android in 48.92ms
√ Updating Android plugins in 3.55ms
[info] Found 4 Capacitor plugins for android:
       @capacitor/app@5.0.6
       @capacitor/haptics@5.0.6
       @capacitor/keyboard@5.0.6
       @capacitor/status-bar@5.0.6
√ update android in 50.47ms
[error] native-run failed with error
        
        ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 34

        More details for this error may be available online:
        https://github.com/ionic-team/native-run/wiki/Android-Errors

**Description:**

I am not able to run npx cap run android

**Command Output:**

  ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 34

        More details for this error may be available online:
        https://github.com/ionic-team/native-run/wiki/Android-Errors

**SDK Info:**

14

**Comment by NelsonDJCR** [comment]
I got the same problem

**Comment by SkySor44** [comment]
Same here. Can there also be added a link or documentation to your wiki of how to download the previous version of the android sdk that is supported? 

I've made very little progress on this when trying download and configure the previous api version

**Comment by sabrien-saber** [comment]
i have same problem

**Comment by jacobwod** [comment]
I'm also getting `ERR_UNSUPPORTED_API_LEVEL`. Clean install of Android Studio on macOS 13. The following SDKs (Platform and Build Tools) are installed (both v33 and v34, as you can see in the screenshots below):

![Skärmavbild 2023-12-08 kl  13 35 10](https://github.com/ionic-team/native-run/assets/110222/a2a9af41-351f-4fc9-aa71-0d5238d2ef26)
![Skärmavbild 2023-12-08 kl  13 35 15](https://github.com/ionic-team/native-run/assets/110222/e5caed2a-904b-4769-bc6e-90669e6c9eb5)


It's worth noting that **uninstalling v34 while leaving the supported v33 does not solve the issue** as it results in `ERR_UNSUITABLE_API_INSTALLATION` instead. 

---

My guess is that we just don't have installed the right combination of SDK Platform and Build tools. Please share if you manage to figure out the correct versions of required components to be installed.

**Comment by ghost** [comment]
I have the same issue here , tried several things but no luck so far

**Comment by ghost** [comment]
![image](https://github.com/ionic-team/native-run/assets/61373609/8c17eb10-d742-4f2a-bf67-4c8fbacc6e8b)

**Comment by ghost** [comment]
fixed by installing this 

![image](https://github.com/ionic-team/native-run/assets/61373609/4a56a275-b0be-4c1b-8d80-b60d32d33e48)

and i have also these installed 

![image](https://github.com/ionic-team/native-run/assets/61373609/a41e6123-db99-4990-ae31-bed28522be19)

**Comment by jcesarmobile** [comment]
this is fixed in native-run 2.0.0, please, update to that version, it was released almost two months ago
