### ISSUE TITLE
ERR_UNSUPPORTED_API_LEVEL error while building ionic android project

### ISSUE THREAD

**Issue by fajarAliM** [ionic-team/native-run#385]
**Version:**

2.0.1

**Description:**

I am getting an error while I am building my ionic project using "npx cap run android". Please check the attached screenshot below
![image](https://github.com/ionic-team/native-run/assets/109135567/826df34a-945d-4e86-b9b8-dcc3215f4e6f)

**Command Output:**
"native-run android --verbose"
![image](https://github.com/ionic-team/native-run/assets/109135567/ab6e5269-bd6b-44a7-9682-b4a23b5beaca)

**SDK Info:**

![image](https://github.com/ionic-team/native-run/assets/109135567/f27f39ca-8c28-454d-85d9-ab4f883fcb33)

**Comment by jcesarmobile** [comment]
`ERR_UNSUPPORTED_API_LEVEL` is no longer present in 2.x code, so you can't be getting that error if using native-run 2.x.

Looks like are still using Capacitor 4, which used native-run 1.x. 

Update to Capacitor 5 or 6
