### ISSUE TITLE
[Ionic Studio] Run on iPhone XS fails

### ISSUE THREAD

**Issue by dotNetkow** [ionic-team/native-run#47]
**Version:** 0.2.2

**Description:**
Running on device not working: On a Mac using Ionic Studio, with an iPhone XS connected to my laptop. Click the Run button, choose my iPhone device, then this appears in the console:

stack trace: 

> native-run ios --app platforms/ios/build/device/Ionifits.ipa --target 00008020-001131182202002E --connect --forward 8100:8100
[native-run] TypeError: Cannot read property 'nodeName' of null
[native-run] at Object.parse (/Users/matt/.ionic/Studio/Tools/lib/node_modules/native-run/node_modules/plist/lib/parse.js:68:25)
[native-run] at UsbmuxdClient.readPairRecord (/Users/matt/.ionic/Studio/Tools/lib/node_modules/native-run/node_modules/node-ioslib/dist/client/usbmuxd.js:80:26)
[native-run] at process._tickCallback (internal/process/next_tick.js:68:7)

**Command Output:**

See above trace.

**Environment Info:**

Ionic:

   Ionic CLI                     : 5.0.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   Cordova CLI       : 9.0.0
   Cordova Platforms : android 8.0.0, ios 5.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 8 other plugins)

Utility:

   cordova-res : 0.3.0
   native-run  : 0.2.2

System:

   Android SDK Tools : 26.1.1 (/Users/matt/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 7.0.0
   NodeJS            : v10.13.0 (/usr/local/bin/node)
   npm               : 6.7.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001

**Comment by tlancina** [comment]
Fixed in 0.2.6.
