### ISSUE TITLE
Error: NO_RESOURCES on iOS physical build

### ISSUE THREAD

**Issue by joanroig** [ionic-team/native-run#48]
I'm trying to run a deploy on iOS with this command, but I get a crash:

`ionic cordova run ios --device --verbose
`

```
native-run ios --app platforms/ios/build/device/App.ipa --device
Error: NO_RESOURCES
    at AFCProtocolReader.callback (/Users/User/Bitbucket/app/node_modules/node-ioslib/dist/protocol/afc.js:129:54)
    at AFCProtocolReader.onData (/Users/User/Bitbucket/app/node_modules/node-ioslib/dist/protocol/protocol.js:52:26)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
[ERROR] An error occurred while running subprocess native-run.
        
        native-run ios --app platforms/ios/build/device/App.ipa
        --device exited with exit code 1.
```

Here is my ionic info:

```
Ionic:

   Ionic CLI                     : 5.0.2
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 25 other plugins)

Utility:

   cordova-res : 0.3.0
   native-run  : 0.2.5

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v12.4.0 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001
```

It properly works on emulator if the device is not attached with this command:
`ionic cordova emulate ios --verbose`

**Comment by tlancina** [comment]
Hey thanks for the report, I'm curious why `--verbose` isn't being passed down to `native-run`.  Can you run `native-run ios --app platforms/ios/build/device/App.ipa --device --verbose` and attach the log here? It will be pretty long, but if I remember right `NO_RESOURCES` happens when the device runs out of fds, so I want to see if we're not freeing them up correctly.

Thanks!

**Comment by chrum** [comment]
got the same problem :(

here is the [result](https://github.com/ionic-team/native-run/files/3291139/native-run-output.txt) of verbosed native-run

**Comment by joanroig** [comment]
@tlancina here it is the log, I think my first log was not with the --verbose but I've tried both, if you need them I can run both again
[native-run-output.txt](https://github.com/ionic-team/native-run/files/3296724/native-run-output.txt)

**Comment by tlancina** [comment]
@joanroig @chrum thank you both, can you please update to 0.2.6 and confirm this fixes the issue, thanks!

**Comment by funkjedi** [comment]
i had the same problem. upgrading to 0.2.6 fixed it for me.

**Comment by tlancina** [comment]
@funkjedi thanks for reporting back, I'm going to close this as fixed.  If anyone is still having issues please feel free to comment or open a new issue.
