### ISSUE TITLE
More reliable adb invocations 

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/native-run#5]
adb is a client/server tool between computer and device and can sometimes get screwed up. 

Add a timeout and retry to all `adb` invocations, being sure to use `adb kill-server`

**Comment by dwieeb** [comment]
Probably not a good idea to kill the adb server because any connections would have to be setup again manually.

**Comment by imhoffd** [comment]
But for the majority of users, this is a nice feature. We can set the timeout to something like 5s and warn when it's reached that we're killing the ADB server.
