### ISSUE TITLE
Error: PasswordProtected

### ISSUE THREAD

**Issue by gravyplaya** [ionic-team/native-run#51]
**Version:**

0.2.6

**Description:**

Ionic app wont run on device or emulator

**Command Output:**
unzipping....
  native-run:ios:utils:app Unzip: Payload/iPrescribe.app/AppIcon76x76~ipad.png +1ms
  client:usbmuxd connectUsbmuxdSocket +0ms
  client:usbmuxd getDevices +2ms
  protocol:usbmux socket write: {"messageType":"ListDevices"} +0ms
  protocol:usbmux Response: {"DeviceList":[{"DeviceID":2,"MessageType":"Attached","Properties":{"ConnectionSpeed":480000000,"ConnectionType":"USB","DeviceID":2,"LocationID":487670016,"ProductID":4776,"SerialNumber":"f8b3d0927f0c488fa1f6ccf08e2b099dde5b0e88"}}]} +450ms
  client:usbmuxd connectUsbmuxdSocket +452ms
  client:usbmuxd connect: 2 on port 62078 +0ms
  protocol:usbmux socket write: {"messageType":"Connect","extraFields":{"DeviceID":2,"PortNumber":32498}} +2ms
  protocol:usbmux Response: {"MessageType":"Result","Number":0} +3ms
  client:lockdownd getAllValues +0ms
  protocol:lockdown socket write: {"Request":"GetValue"} +0ms
  protocol:lockdown Response: {"Request":"GetValue","Value":{"BasebandCertId":3840149528,"BasebandKeyHashInformation":{"AKeyStatus":2,"SKeyHash":{"type":"Buffer","data":[187,239,237,112,44,47,105,15,181,99,219,120,208,142,50,122,0,132,152,29,188,152,2,229,105,19,161,104,133,70,5,106]},"SKeyStatus":0},"BasebandSerialNumber":{"type":"Buffer","data":[5,250,176,106]},"BasebandVersion":"5.60.01","BoardId":4,"BuildVersion":"16F203","ChipID":32768,"DeviceClass":"iPhone","DeviceColor":"#272728","DeviceName":"Geovanni’s iPhone","DieID":5446701835592,"HardwareModel":"N71AP","HasSiDP":true,"PartitionType":"GUID_partition_scheme","ProductName":"iPhone OS","ProductType":"iPhone8,1","ProductVersion":"12.3.1","ProductionSOC":true,"ProtocolVersion":"2","TelephonyCapability":true,"UniqueChipID":5446701835592,"UniqueDeviceID":"f8b3d0927f0c488fa1f6ccf08e2b099dde5b0e88","WiFiAddress":"cc:20:e8:0f:5e:c8"}} +42ms
  client:usbmuxd connectUsbmuxdSocket +47ms
  client:usbmuxd getDevice udid: f8b3d0927f0c488fa1f6ccf08e2b099dde5b0e88 +1ms
  client:usbmuxd getDevices +1ms
  protocol:usbmux socket write: {"messageType":"ListDevices"} +45ms
  protocol:usbmux Response: {"DeviceList":[{"DeviceID":2,"MessageType":"Attached","Properties":{"ConnectionSpeed":480000000,"ConnectionType":"USB","DeviceID":2,"LocationID":487670016,"ProductID":4776,"SerialNumber":"f8b3d0927f0c488fa1f6ccf08e2b099dde5b0e88"}}]} +1ms
  client:usbmuxd readPairRecord: f8b3d0927f0c488fa1f6ccf08e2b099dde5b0e88 +2ms
  client:usbmuxd connect: 2 on port 62078 +11ms
  protocol:usbmux socket write: {"messageType":"Connect","extraFields":{"DeviceID":2,"PortNumber":32498}} +8ms
  protocol:usbmux Response: {"MessageType":"Result","Number":0} +1ms
  client:lockdownd doHandshake +59ms
  client:lockdownd startSession: [object Object] +1ms
  protocol:lockdown socket write: {"Request":"StartSession","HostID":"3693925C-8375-451D-ACE6-96462BE7BC34","SystemBUID":"A2CF7ACA-BB5B-412F-B5A3-05D1B8BAA5BA"} +17ms
  protocol:lockdown Response: {"EnableSessionSSL":true,"Request":"StartSession","SessionID":"991ADDAC-F0BB-4C11-935F-82D634F26239"} +3ms
  client:lockdownd Socket upgraded to TLS connection +13ms
  client:lockdownd startService: com.apple.mobile.mobile_image_mounter +1ms
  protocol:lockdown socket write: {"Request":"StartService","Service":"com.apple.mobile.mobile_image_mounter"} +11ms
  protocol:lockdown Response: {"Error":"PasswordProtected","Request":"StartService"} +78ms
  native-run Caught fatal error: Error: PasswordProtected
  native-run     at LockdownProtocolReader.parseBody (/Users/geo/.nvm/versions/node/v8.15.1/lib/node_modules/native-run/node_modules/node-ioslib/dist/protocol/lockdown.js:35:19)
  native-run     at LockdownProtocolReader.onData (/Users/geo/.nvm/versions/node/v8.15.1/lib/node_modules/native-run/node_modules/node-ioslib/dist/protocol/protocol.js:52:40)
  native-run     at emitOne (events.js:116:13)
  native-run     at TLSSocket.emit (events.js:211:7)
  native-run     at addChunk (_stream_readable.js:263:12)
  native-run     at readableAddChunk (_stream_readable.js:250:11)
  native-run     at TLSSocket.Readable.push (_stream_readable.js:208:10)
  native-run     at TLSWrap.onread (net.js:601:20) +0ms
Error: PasswordProtected
    at LockdownProtocolReader.parseBody (/Users/geo/.nvm/versions/node/v8.15.1/lib/node_modules/native-run/node_modules/node-ioslib/dist/protocol/lockdown.js:35:19)
    at LockdownProtocolReader.onData (/Users/geo/.nvm/versions/node/v8.15.1/lib/node_modules/native-run/node_modules/node-ioslib/dist/protocol/protocol.js:52:40)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:601:20)

**Environment Info:**

Ionic:

   Ionic CLI         : 5.0.1 (/Users/geo/.nvm/versions/node/v8.15.1/lib/node_modules/ionic)
   Ionic Framework   : ionic1 master
   @ionic/v1-toolkit : 2.0.3

Cordova:

   Cordova CLI       : 7.1.0
   Cordova Platforms : android 6.3.0, ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 24 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.6

System:

   Android SDK Tools : 26.1.1 (/Users/geo/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 6.1.3
   NodeJS            : v8.15.1 (/Users/geo/.nvm/versions/node/v8.15.1/bin/node)
   npm               : 2.15.12
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001

macOS version: 10.14.4

Xcode version: 10.2.1

**Comment by gravyplaya** [comment]
same error on ios and android

**Comment by tlancina** [comment]
This seems to be an iOS device specific error, so if you are getting errors when running on the iOS simulator please add them.

I'm not sure when `PasswordProtected` happens, but I would assume it's because your iOS device has a password set somehow? I would love to know more if you know why it might be throwing that error.

I'm going to close this for now, please feel free to add more information and I will re-open, thanks.
