### ISSUE TITLE
ERR_SDK_PACKAGE_NOT_FOUND executing ionic cordova run android

### ISSUE THREAD

**Issue by brune83** [ionic-team/native-run#53]
**Version:**

0.2.6

**Description:**

Running the command `ionic cordova run android` I get the error `ERR_SDK_PACKAGE_NOT_FOUND`

**Command Output:**

2019-06-22T15:11:54.995Z native-run:android:utils:sdk:getSDKPackage Encountered error with C:\Program Files (x86)\Android\android-sdk\platform-tools\package.xml: { [Error: ENOENT: no such file or directory, open 'C:\Program Files (x86)\Android\android-sdk\platform-tools\package.xml']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'C:\\Program Files (x86)\\Android\\android-sdk\\platform-tools\\package.xml' }
ERR_SDK_PACKAGE_NOT_FOUND: SDK package not found by location: C:\Program Files (x86)\Android\android-sdk\platform-tools.
2019-06-22T15:11:54.996Z native-run Caught fatal error: { Error: SDK package not found by location: C:\Program Files (x86)\Android\android-sdk\platform-tools.
    at Object.getSDKPackage (C:\Users\Alessandro\AppData\Roaming\npm\node_modules\native-run\dist\android\utils\sdk\index.js:90:23)
  code: 'ERR_SDK_PACKAGE_NOT_FOUND',
  exitCode: 1,
  data: undefined }
[ERROR] An error occurred while running subprocess native-run.

        native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-d... exited with exit code 1.

**SDK Info:**

SDK Location:         C:\Program Files (x86)\Android\android-sdk
AVD Home:             C:\Users\Alessandro\.android\avd

Tools:

**Comment by dwieeb** [comment]
@brune83 Do you have the Android Platform Tools installed?

**Comment by brune83** [comment]
Yes, I have.
I updated it to 29.0.1, but in the folder there is no 'package.xml' file.

**Comment by dwieeb** [comment]
What are the contents of the directory? It may not have installed successfully. Are you able to run your app in Android Studio?

**Comment by brune83** [comment]
I didn't try to run my app in Android Studio, but I downloaded also the Android Platform Tools from here:

[https://developer.android.com/studio/releases/platform-tools](https://developer.android.com/studio/releases/platform-tools)

and I can see that the contents of my directory are right: it seems that in Android Platform Tools version 29.0.1 the file 'package.xml' does not exist...

**Comment by dwieeb** [comment]
Ahh, okay. The `package.xml` is a file for the package in the Android Repository. Without it, native-run isn't able to know what it is. 

Is there a reason you downloaded platform-tools directly instead of using the SDK Manager inside of Android Studio?

**Comment by brune83** [comment]
I downloaded it with Android SDK Manager as usual actually...
Then I tried to download it directly from Google website to check if the contents of my platform-tools were right, and it seems they are.
So, am I the only without the package.xml inside the directory or it's a problem with the new Android Platform Tools version?

**Comment by dwieeb** [comment]
I have Android Platform Tools 29.0.1 and it includes a `package.xml`. I also tried uninstalling and reinstalling it.

**Comment by brune83** [comment]
I also tried uninstalling and reinstalling, but I had no luck...
I am on Windows, I don't know if this information can be useful.

**Comment by dwieeb** [comment]
On my Windows machine, the `platform-tools` directory has `package.xml`. It's really odd that yours doesn't! I am using Android Studio 3.4 to install/reinstall packages.

**Comment by brune83** [comment]
A friend sent me the package.xml file, I copied that into the platform-tools folder and everything worked.
I still don't know why I don't have this file, but for sure this is not a problem related to native-run project.
So, I think you can close this issue.
Thanks for your support.

**Comment by dwieeb** [comment]
@brune83 Alright. Glad to hear it's working for you. Very strange. Let me know if that happens again. `native-run` should be resilient to Android package changes. Thanks!

**Comment by MichaelApproved** [comment]
I had the same issue and resolved it by running the following command: `sdkmanager --list`

sdkmanager.bat is a batch file that was in `C:\Program Files (x86)\Android\android-sdk\tools\bin\` but it might be in another location on your computer. Go to that folder within the command prompt and run the `sdkmanager --list` command.

After I ran that command, the package.xml file appeared in the directory and resolved the ERR_SDK_PACKAGE_NOT_FOUND error.

**Comment by Kirubha03** [comment]
Actually I Had same issue after installing latest Ionic version 5.2.3.In this I can able to build apk. But when use  `ionic cordova run android`  it throws error `ERR_SDK_PACKAGE_NOT_FOUND`  Error. So I tried
1. I did install/reinstalled android SDK
2. Updated platform_tools
3. used sdkmanager.bat  for list.

So above all methods not working. Still I'm having same issue.  I think this issue still open state. Anyone can help to solve this...

**Comment by dex252** [comment]
Check it. I have the same problem. https://chromium.googlesource.com/android_tools/+/347a7c8078a009e98995985b7ab6ec6b35696dea

**Comment by paolosanchi** [comment]
> I had the same issue and resolved it by running the following command: `sdkmanager --list`
> 
> sdkmanager.bat is a batch file that was in `C:\Program Files (x86)\Android\android-sdk\tools\bin\` but it might be in another location on your computer. Go to that folder within the command prompt and run the `sdkmanager --list` command.
> 
> After I ran that command, the package.xml file appeared in the directory and resolved the ERR_SDK_PACKAGE_NOT_FOUND error.

Worked! Just remember to execute the command shell as administrator
