### ISSUE TITLE
Improve error messaging

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/native-run#7]

**Comment by falquinho** [comment]
Just to add to this. Today I updated Ionic to 5.0.0 and now I have to use native-run.
I then proceed to deploy my app like always: "ionic cordova run android --device"
Then native-run erros out with a cryptic message "ERR_UNSUITABLE_API_INSTALLATION", leading me to believe something is broken with my install. I had to look the source in github to understand it was looking for an AVD and it did not found one.
So, yeah, tl;dr make error messages clear.

**Comment by dwieeb** [comment]
@falquinho This should be improved in the next release! Let me know your thoughts it when you see it! Thanks for your feedback.
