### ISSUE TITLE
native-run not working from ionic cordova run ios --device

### ISSUE THREAD

**Issue by mmccorkleaccesso** [ionic-team/native-run#75]
**Version:**

0.2.8

**Description:**

Cannot install to device using ionic cordova run ios --device. Standard command from native-run works fine. 
This works.
`native-run ios --app platforms/ios/build/device/myapp.ipa`

This does not work.
`ionic cordova run ios --device`

**Command Output:**

native-run ios --app platforms/ios/build/device/
		myapp
	.ipa --device
[native-run] ERR_UNKNOWN: Path 'platforms/ios/build/device/
[native-run] 		myapp
[native-run] 	.ipa' not found
[ERROR] An error occurred while running subprocess native-run.
        
        native-run ios --app platforms/ios/build/device/
        		myapp
        	.ipa --device exited with exit code 1.

**Environment Info:**

Ionic:

   Ionic CLI                     : 5.2.5 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 21 other plugins)

Utility:

   cordova-res : 0.3.0 (update available: 0.6.0)
   native-run  : 0.2.8 

System:

   Android SDK Tools : 26.1.1 (/Users/markmccorkle/Library/Android/sdk/)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v10.16.2 (/usr/local/Cellar/node@10/10.16.2/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8
macOS version:

Xcode version:

**Comment by xmarkclx** [comment]
I have this problem. What did you do?

**Comment by tatianilima** [comment]
Same problem here. What did you do? I have a Macbook too

**Comment by J4cku** [comment]
Anyone can help with that? Why was it closed?

**Comment by imhoffd** [comment]
This is likely an issue with the Ionic CLI, would you mind [creating a new issue there](https://github.com/ionic-team/ionic-cli/issues)?

**Comment by J4cku** [comment]
Just did that (even added small repo to reproduce):
https://github.com/ionic-team/ionic-cli/issues/4561

**Comment by imhoffd** [comment]
@J4cku That doesn't look like the same problem. In fact, your issue _is_ an issue with native-run. I'll move it.
