### ISSUE TITLE
[native-run] ERR_AVD_HOME_NOT_FOUND: No valid Android AVD home found.

### ISSUE THREAD

**Issue by LudwigBrio** [ionic-team/native-run#91]
**Native run Version:** 0.2.9
**Ionic cli Version:** 5.4.9

**Description:** I want to run the following command `sudo ionic cordova run android --device` but I have the error below

**Command Output:** 
![image](https://user-images.githubusercontent.com/51226728/69689680-86f58480-1104-11ea-8faa-72904981b927.png)

**SDK Info:**
![image](https://user-images.githubusercontent.com/51226728/69689711-a096cc00-1104-11ea-8b59-f1ab34764faa.png)

**Comment by dwieeb** [comment]
If you're using `sudo`, then the command runs as a different user. It won't find the AVD home in your home directory because it's using a different home directory. Don't use `sudo` with Ionic.

**Comment by LudwigBrio** [comment]
Hello I open again this issue because, I have the same issue and I cannot run `ionic cordova run android --device` without `sudo`. Do you know How I can do it please?
